# name: Docker Image CI

# on:
#   push:
#     branches:
#       - master

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v1
#     - name: docker login
#       uses: actions/docker/login@master
#       env:
#         DOCKER_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
#         DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
#         run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD huseyinyilmaz/actixtest:latest
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag huseyinyilmaz/actixtest:latest
#     - name: docker build
#       uses: actions/docker/cli@master
#       with:
#         args: build -t huseyinyilmaz/actixtest:latest -f Dockerfile .
#     - name: docker push
#       uses: actions/docker/cli@master
#       with:
#         args: push huseyinyilmaz/actixtest:latest
name: Publish to Dockerhub
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: huseyinyilmaz/web_exporter
        tag_with_ref: true
