name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: docker login
      uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD huseyinyilmaz/web_exporter:latest
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag huseyinyilmaz/web_exporter:latest
    - name: docker build
      uses: actions/docker/cli@master
      with:
        args: build -t huseyinyilmaz/web_exporter:latest -f Dockerfile .
    - name: docker push
      uses: actions/docker/cli@master
      with:
        args: push huseyinyilmaz/web_exporter:latest
